# Generated by Django 4.1 on 2022-09-02 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuthGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
            ],
            options={"db_table": "auth_group", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthGroupPermissions",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "auth_group_permissions", "managed": False,},
        ),
        migrations.CreateModel(
            name="AuthPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("codename", models.CharField(max_length=100)),
            ],
            options={"db_table": "auth_permission", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoAdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action_time", models.DateTimeField()),
                ("object_id", models.TextField(blank=True, null=True)),
                ("object_repr", models.CharField(max_length=200)),
                ("action_flag", models.PositiveSmallIntegerField()),
                ("change_message", models.TextField()),
            ],
            options={"db_table": "django_admin_log", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoContentType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
            ],
            options={"db_table": "django_content_type", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoMigrations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("app", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("applied", models.DateTimeField()),
            ],
            options={"db_table": "django_migrations", "managed": False,},
        ),
        migrations.CreateModel(
            name="DjangoSession",
            fields=[
                (
                    "session_key",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("session_data", models.TextField()),
                ("expire_date", models.DateTimeField()),
            ],
            options={"db_table": "django_session", "managed": False,},
        ),
        migrations.CreateModel(
            name="UsersGroups",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "users_groups", "managed": False,},
        ),
        migrations.CreateModel(
            name="UsersUserPermissions",
            fields=[("id", models.BigAutoField(primary_key=True, serialize=False)),],
            options={"db_table": "users_user_permissions", "managed": False,},
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("questionid", models.AutoField(primary_key=True, serialize=False)),
                ("questioncontent", models.TextField(blank=True, null=True)),
                ("answer", models.CharField(blank=True, max_length=128, null=True)),
                ("explaination", models.TextField(blank=True, null=True)),
                ("passnumber", models.IntegerField(blank=True, null=True)),
                ("trynumber", models.IntegerField(blank=True, null=True)),
                ("passusers", models.TextField(blank=True, null=True)),
                ("difficulty", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "questions", "managed": True,},
        ),
        migrations.CreateModel(
            name="Users",
            fields=[
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("is_superuser", models.IntegerField(default=0)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                ("is_staff", models.IntegerField(default=0)),
                ("is_active", models.IntegerField(default=0)),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("userid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=128, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(blank=True, max_length=128, null=True)),
                ("email", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "phonenumber",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("cookiepoints", models.IntegerField(blank=True, null=True)),
                ("level", models.IntegerField(blank=True, null=True)),
                ("questionscompleted", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "users", "managed": True,},
        ),
    ]
